import type { Metadata } from "next";

import "./globals.css";
import { fontVariables } from "@/font";
import Provider from "./provider";

export const metadata: Metadata = {
  title: "Spawnkit",
  description: "Generated by 'npx spawnkit@latest init'",
  icons: "/logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontVariables("antialiased")}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
